import Navbar from "@/components/Navbar";
import RefreshToken from "@/components/RefreshToken";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning={true} lang="en">
      <body className="min-h-screen">
        <AntdRegistry>
          <Navbar />
          <RefreshToken />
          {children}
        </AntdRegistry>
      </body>
    </html>
  );
}
